state_machine_controller:
  ros__parameters:
    explore_linear_speed: 0.18
    follow_linear_speed: 0.14
    skip_tag1_return: false

safety_controller:
  ros__parameters:
    hard_stop_distance_m: 0.35
