vision_processor:
  ros__parameters:
    # SDF alignment:
    #   physical tag0 -> logical Tag 2
    #   physical tag1 -> logical Tag 1
    #   physical tag2 -> logical Tag 3
    #   physical tag3 -> logical Tag 4
    #   physical tag4 -> logical Tag 5
    tag_id_to_label: [2, 1, 3, 4, 5]
